# Generated by Django 3.2.5 on 2022-08-07 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
