# Generated by Django 3.2.5 on 2022-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='customer',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default='hjh', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expenses_category',
            field=models.CharField(default='jdjuid', max_length=500),
            preserve_default=False,
        ),
    ]
