# Generated by Django 3.2.5 on 2022-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='media_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
