# Generated by Django 3.2.5 on 2022-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
