# Generated by Django 3.2.5 on 2022-08-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220807_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='dateEvent',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
