# Generated by Django 3.2.5 on 2022-09-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.CharField(max_length=500)),
                ('linkedin_link', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Finance', 'Finance'), ('Business', 'Business'), ('Sales', 'Sales'), ('Mindset', 'Mindset')], default='Accounting', max_length=100),
        ),
    ]
