# Generated by Django 3.2.5 on 2022-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
