# Generated by Django 3.2.5 on 2022-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220807_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsolditem',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashsolditemcustomer',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesolditem',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
