# Generated by Django 3.2.5 on 2022-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220701_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsale',
            name='amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
