# Generated by Django 3.2.5 on 2022-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='color',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='dateEvent',
            field=models.CharField(default='01-01-2022', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='description',
            field=models.TextField(default='sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='endTime',
            field=models.CharField(default='00:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='remind',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='repeat',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shedule',
            name='startTime',
            field=models.CharField(default='00:00', max_length=15),
            preserve_default=False,
        ),
    ]
