# Generated by Django 3.2.5 on 2022-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220701_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
