# Generated by Django 3.2.5 on 2022-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_selling_price_secondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_category', models.CharField(choices=[('thank-you', 'Thank You'), ('offers', 'Offers'), ('good-morning', 'Good Morning')], max_length=100)),
                ('greeting_card', models.ImageField(upload_to='greeting-cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
