# Generated by Django 3.2.5 on 2022-09-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220924_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.authorblog'),
        ),
    ]
