# Generated by Django 3.2.5 on 2022-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220711_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsolditem',
            name='customer',
        ),
    ]
