# Generated by Django 3.2.5 on 2022-08-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220807_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='business_name',
            field=models.CharField(default='--', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='---', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default='---', max_length=50),
            preserve_default=False,
        ),
    ]
