# Generated by Django 3.2.5 on 2022-07-31 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220731_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
