# Generated by Django 3.2.5 on 2022-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220731_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsolditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cashsolditemcustomer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoicesolditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='product',
        ),
        migrations.AddField(
            model_name='cashsolditem',
            name='product_name',
            field=models.CharField(default='product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashsolditemcustomer',
            name='product_name',
            field=models.CharField(default='product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesolditem',
            name='product_name',
            field=models.CharField(default='product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='product_name',
            field=models.CharField(default='product', max_length=100),
            preserve_default=False,
        ),
    ]
