# Generated by Django 3.2.5 on 2022-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_greetingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingcard',
            name='default_text',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
