# Generated by Django 3.2.5 on 2022-07-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cashsolditem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
