# Generated by Django 3.2.5 on 2022-08-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220810_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_invoice',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_purchase',
        ),
    ]
