# Generated by Django 3.2.5 on 2022-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authorblog_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorblog',
            name='avatar',
            field=models.ImageField(null=True, upload_to='author/'),
        ),
    ]
