# Generated by Django 3.2.5 on 2022-07-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_payment_receipt_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(default='123', max_length=50)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='cashsale',
            name='receipt_no',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='bill_no',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_no',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.CreateModel(
            name='CashSoldItemCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_unit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_sale_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cashsalecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='cashsalecustomer',
            name='sold_items',
            field=models.ManyToManyField(blank=True, related_name='sales_data_customer', to='home.CashSoldItemCustomer'),
        ),
    ]
