# Generated by Django 3.2.5 on 2022-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_inventorytrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytrack',
            name='purchases_price',
            field=models.IntegerField(default=0),
        ),
    ]
