# Generated by Django 3.2.5 on 2022-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220716_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
