# Generated by Django 3.2.5 on 2022-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220706_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='balance_due',
        ),
        migrations.AlterField(
            model_name='cashsolditem',
            name='product_unit',
            field=models.CharField(default='Items', max_length=100),
            preserve_default=False,
        ),
    ]
