# Generated by Django 3.2.5 on 2022-07-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220709_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.CharField(default='Purchases', max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='product_unit',
            field=models.CharField(default='Items', max_length=100),
        ),
    ]
