# Generated by Django 3.2.5 on 2022-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_is_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchases_price',
            field=models.IntegerField(default=0),
        ),
    ]
