# Generated by Django 3.2.5 on 2022-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220709_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expenses_category',
            field=models.CharField(choices=[('direct', 'Direct Expenses'), ('indirect', 'Indirect Expenses')], max_length=200),
        ),
    ]
