# Generated by Django 3.2.5 on 2022-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_versiontrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsolditem',
            name='purchases_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashsolditemcustomer',
            name='purchases_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicesolditem',
            name='purchases_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
