# Generated by Django 3.2.5 on 2022-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220828_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsale',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cashsalecustomer',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
