# Generated by Django 3.2.5 on 2022-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_expense_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='Expenses', max_length=500),
        ),
    ]
