# Generated by Django 3.2.5 on 2022-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_purchases_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
