# Generated by Django 3.2.5 on 2022-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_expense_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseditem',
            old_name='cash_sale_data',
            new_name='purchases_data',
        ),
    ]
