# Generated by Django 3.2.5 on 2022-09-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blogging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogging',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='blogging',
            name='slug',
            field=models.SlugField(default='sample', unique=True),
            preserve_default=False,
        ),
    ]
