# Generated by Django 3.2.5 on 2022-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220723_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsalecustomer',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
