# Generated by Django 3.2.5 on 2022-09-21 23:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220922_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('metadata', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('published', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(upload_to='tutorial/')),
                ('slug', models.SlugField(unique=True)),
                ('english', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
