# Generated by Django 3.2.5 on 2022-09-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='slug',
        ),
    ]
