# Generated by Django 3.2.5 on 2022-05-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_database',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_emails',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_feedbacks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_gbv_reports',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_message',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_sms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='access_whatsapp',
        ),
    ]
